name: shell-commend
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: display working directory and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
  run-shell-commands-windows:
    runs-on: windows-latest
    steps:
      - name: display working directory and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
